/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#d5e3fd",
        "primary-container": "#131b2e",
        "surface-container-high": "#e6e8ea",
        "inverse-primary": "#bec6e0",
        "tertiary-fixed": "#acedff",
        "surface-tint": "#565e74",
        "on-secondary-container": "#57657b",
        "on-background": "#191c1e",
        "surface-variant": "#e0e3e5",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "background": "#f7f9fb",
        "surface-container-highest": "#e0e3e5",
        "secondary": "#515f74",
        "on-surface": "#191c1e",
        "inverse-surface": "#2d3133",
        "surface-bright": "#f7f9fb",
        "on-error-container": "#93000a",
        "surface-container-low": "#f2f4f6",
        "tertiary": "#000000",
        "primary": "#000000",
        "inverse-on-surface": "#eff1f3",
        "on-tertiary-fixed": "#001f26",
        "outline": "#76777d",
        "on-surface-variant": "#45464d",
        "on-secondary-fixed-variant": "#3a485c",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#0090a9",
        "tertiary-container": "#001f26",
        "secondary-container": "#d5e3fd",
        "primary-fixed-dim": "#bec6e0",
        "on-secondary": "#ffffff",
        "surface-dim": "#d8dadc",
        "tertiary-fixed-dim": "#4cd7f6",
        "on-primary-fixed": "#131b2e",
        "surface-container": "#eceef0",
        "surface-container-lowest": "#ffffff",
        "surface": "#f7f9fb",
        "on-secondary-fixed": "#0d1c2f",
        "on-primary-fixed-variant": "#3f465c",
        "outline-variant": "#c6c6cd",
        "on-tertiary-fixed-variant": "#004e5c",
        "primary-fixed": "#dae2fd",
        "secondary-fixed-dim": "#b9c7e0",
        "on-primary-container": "#7c839b",
        "on-error": "#ffffff"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      }
    },
  },
  plugins: [],
};
